version: '3'

services:
  database_pg:
    image: bitnami/postgresql:latest
    container_name: postgres_prisma
    ports:
      - "5433:5432"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=api_express_prisma